version: "2.1"

services:

  blue-calc:
    container_name: "blue-calc"
    image: registry.red.lab.aonanalytics.com/ios-calc:latest
    restart: always
    environment:
      - VIRTUAL_HOST=blue.dev.lab.aonanalytics.com
      - VIRTUAL_PORT=3000
    ports:
      - 3001:3000

  green-calc:
    container_name: "green-calc"
    image: registry.red.lab.aonanalytics.com/ios-calc:latest
    restart: always
    environment:
      - VIRTUAL_HOST=green.dev.lab.aonanalytics.com, calc.dev.lab.aonanalytics.com
      - VIRTUAL_PORT=3000
    ports:
      - 3002:3000
