version: "2.1"

services:

  calc:
    container_name: "calc"
    image: registry.red.lab.aonanalytics.com/ios-calc:v1.0
    restart: always
    environment:
      - VIRTUAL_HOST=calc.prodtest.lab.aonanalytics.com
      - VIRTUAL_PORT=3000
    ports:
      - 3001:3000
