version: "2.1"

services:

  ios-calc:
    container_name: "ios-calc"
    image: registry.red.lab.aonanalytics.com/ios-calc:latest
    restart: always
    environment:
      - VIRTUAL_HOST=calc.dev.lab.aonanalytics.com
      - VIRTUAL_PORT=3000
    ports:
      - 3000:3000
